INSERT INTO `oc_emailtemplate_shortcode` (`emailtemplate_shortcode_code`, `emailtemplate_shortcode_type`, `emailtemplate_shortcode_example`, `emailtemplate_id`) VALUES
('text_thanks', 'language', 'Thanks,', {_ID}),
('text_customer_welcome', 'language', 'Your return request has been sent to the relevant department for processing. You will be notified again via e-mail when the status of your request changes.', {_ID}),
('text_customer_greeting', 'language', 'Thank you for your recent order at {{ store_name }}', {_ID}),
('text_customer_subject', 'language', 'We have received the return for Order: {{ order_id }}', {_ID}),
('text_telephone', 'language', 'Telephone', {_ID}),
('text_subject', 'language', '{{ store_name }} Return Details', {_ID}),
('text_return_id', 'language', 'Return ID:', {_ID}),
('text_return_detail', 'language', 'Return Details', {_ID}),
('text_return', 'language', 'Return Information', {_ID}),
('text_return_date', 'language', 'Return Details', {_ID}),
('text_reason', 'language', 'Reason', {_ID}),
('text_order_total', 'language', 'Order Total:', {_ID}),
('text_order_date', 'language', 'Order Date:', {_ID}),
('text_order_id', 'language', 'Order ID:', {_ID}),
('text_order', 'language', 'Order Information', {_ID}),
('text_opened', 'language', 'Opened:', {_ID}),
('text_model', 'language', 'Model:', {_ID}),
('text_date', 'language', 'Date:', {_ID}),
('text_name', 'language', 'Name:', {_ID}),
('text_greeting', 'language', 'A new product return has been placed at: {{ store_name }}', {_ID}),
('text_greeting_customer', 'language', 'Your return has been submitted at: {{ store_name }}', {_ID}),
('text_email', 'language', 'E-Mail:', {_ID}),
('text_action', 'language', 'Login into admin for further details', {_ID}),
('text_comment', 'language', 'Return Comments:', {_ID}),
('text_view_browser', 'language', 'If you\'re having difficulty viewing this email <a href=\"%s\" target=\"_blank\">open in a browser</a>.', {_ID}),
('text_total', 'language', 'Total', {_ID}),
('text_rating', 'language', 'Rating', {_ID}),
('text_quantity', 'language', 'Quantity', {_ID}),
('text_price', 'language', 'Price', {_ID}),
('text_product', 'language', 'Product', {_ID}),
('text_emailtemplate_footer', 'language', '&lt;div&gt;\r\n&lt;table cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; style=&quot;width:100%&quot;&gt;\r\n	&lt;tbody&gt;\r\n		&lt;tr&gt;\r\n			&lt;td height=&quot;10&quot; style=&quot;font-size:1px; line-height:10px; mso-margin-top-alt:1px&quot;&gt;&amp;nbsp;&lt;/td&gt;\r\n		&lt;/tr&gt;\r\n		&lt;tr&gt;\r\n			&lt;td style=&quot;color:#666666; font-size:13px&quot;&gt;If you have any questions please do not hesitate to contact us via our &lt;a href=&quot;{{ contact_url }}&quot;&gt;website contact us form&lt;/a&gt;, email: &lt;a href=&quot;mailto:{{ store_email }}&quot;&gt;{{ store_email }}&lt;/a&gt; or phone us on &lt;a href=&quot;tel:{{ store_telephone }}&quot; style=&quot;    white-space: nowrap;&quot;&gt;{{ store_telephone }}&lt;/a&gt; and we will be happy to help.&amp;nbsp;&lt;/td&gt;\r\n		&lt;/tr&gt;\r\n		&lt;tr&gt;\r\n			&lt;td height=&quot;5&quot; style=&quot;font-size:1px; line-height:5px; mso-margin-top-alt:1px&quot;&gt;&amp;nbsp;&lt;/td&gt;\r\n		&lt;/tr&gt;\r\n		&lt;tr&gt;\r\n			&lt;td&gt;&lt;strong&gt;{{ store_name }}&lt;/strong&gt;&lt;/td&gt;\r\n		&lt;/tr&gt;\r\n	&lt;/tbody&gt;\r\n&lt;/table&gt;\r\n&lt;/div&gt;\r\n', {_ID}),
('text_emailtemplate_cart_title', 'language', '{{ customer_firstname }} you\'ve left something in your cart', {_ID}),
('button_cart_checkout', 'language', 'Finish Order', {_ID}),
('datepicker', 'language', 'en-gb', {_ID}),
('error_curl', 'language', 'CURL: Error Code(%s): %s', {_ID}),
('error_upload_999', 'language', 'Warning: No error code available!', {_ID}),
('error_upload_8', 'language', 'Warning: File upload stopped by extension!', {_ID}),
('error_upload_7', 'language', 'Warning: Failed to write file to disk!', {_ID}),
('error_upload_6', 'language', 'Warning: Missing a temporary folder!', {_ID}),
('error_upload_4', 'language', 'Warning: No file was uploaded!', {_ID}),
('error_upload_3', 'language', 'Warning: The uploaded file was only partially uploaded!', {_ID}),
('error_upload_2', 'language', 'Warning: The uploaded file exceeds the MAX_FILE_SIZE directive that was specified in the HTML form!', {_ID}),
('error_upload_1', 'language', 'Warning: The uploaded file exceeds the upload_max_filesize directive in php.ini!', {_ID}),
('error_exception', 'language', 'Error Code(%s): %s in %s on line %s', {_ID}),
('button_map', 'language', 'View Google Map', {_ID}),
('button_grid', 'language', 'Grid', {_ID}),
('button_list', 'language', 'List', {_ID}),
('button_quote', 'language', 'Get Quotes', {_ID}),
('button_reward', 'language', 'Apply Points', {_ID}),
('button_upload', 'language', 'Upload File', {_ID}),
('button_voucher', 'language', 'Apply Gift Certificate', {_ID}),
('button_view', 'language', 'View', {_ID}),
('button_guest', 'language', 'Guest Checkout', {_ID}),
('button_submit', 'language', 'Submit', {_ID}),
('button_shipping', 'language', 'Apply Shipping', {_ID}),
('button_search', 'language', 'Search', {_ID}),
('button_shopping', 'language', 'Continue Shopping', {_ID}),
('button_return', 'language', 'Return', {_ID}),
('button_reorder', 'language', 'Reorder', {_ID}),
('button_remove', 'language', 'Remove', {_ID}),
('button_update', 'language', 'Update', {_ID}),
('button_login', 'language', 'Login', {_ID}),
('button_write', 'language', 'Write Review', {_ID}),
('button_reviews', 'language', 'Reviews', {_ID}),
('button_change_address', 'language', 'Change Address', {_ID}),
('button_new_address', 'language', 'New Address', {_ID}),
('button_filter', 'language', 'Refine Search', {_ID}),
('button_edit', 'language', 'Edit', {_ID}),
('button_download', 'language', 'Download', {_ID}),
('button_delete', 'language', 'Delete', {_ID}),
('button_coupon', 'language', 'Apply Coupon', {_ID}),
('button_confirm', 'language', 'Confirm Order', {_ID}),
('button_checkout', 'language', 'Checkout', {_ID}),
('button_wishlist', 'language', 'Add to Wish List', {_ID}),
('button_compare', 'language', 'Compare this Product', {_ID}),
('button_cancel', 'language', 'Cancel', {_ID}),
('button_cart', 'language', 'Add to Cart', {_ID}),
('button_continue', 'language', 'Continue', {_ID}),
('button_back', 'language', 'Back', {_ID}),
('button_address_add', 'language', 'Add Address', {_ID}),
('text_no_results', 'language', 'No results!', {_ID}),
('text_all_zones', 'language', 'All Zones', {_ID}),
('text_pagination', 'language', 'Showing %d to %d of %d (%d Pages)', {_ID}),
('text_yes', 'language', 'Yes', {_ID}),
('text_no', 'language', 'No', {_ID}),
('text_home', 'language', '<i class=\"fa fa-home\"></i>', {_ID}),
('datetime_format', 'language', 'd/m/Y H:i:s', {_ID}),
('time_format', 'language', 'h:i:s A', {_ID}),
('date_format_long', 'language', 'l dS F Y', {_ID}),
('date_format_short', 'language', 'd/m/Y', {_ID}),
('code', 'language', 'en', {_ID}),
('direction', 'language', 'ltr', {_ID}),
('customer.newsletter', 'auto', '1', {_ID}),
('customer.address_id', 'auto', '4', {_ID}),
('customer.ip', 'auto', '172.16.238.1', {_ID}),
('customer.status', 'auto', '1', {_ID}),
('customer.safe', 'auto', '0', {_ID}),
('customer.date_added', 'auto', '2021-07-06 11:30:42', {_ID}),
('return_date', 'auto', '06/07/2021', {_ID}),
('preference_text', 'auto', '<div>You\'re receiving this email because�of your�<a href=\"https://oc.local/\">Your Store</a> account. <a href=\"\">Manage your email preference</a> | <a href=\"https://oc.local/index.php?route=information/information&amp;information_id=3\">Privacy policy</a></div>', {_ID}),
('customer.store_id', 'auto', '0', {_ID}),
('customer.language_id', 'auto', '1', {_ID}),
('customer.firstname', 'auto', 'John', {_ID}),
('customer.lastname', 'auto', 'Smith', {_ID}),
('customer.email', 'auto', 'user@oc.local', {_ID}),
('customer.telephone', 'auto', '0123456789', {_ID}),
('customer.salt', 'auto', 'GXSF5P2xw', {_ID}),
('customer.customer_group_id', 'auto', '1', {_ID}),
('customer.customer_id', 'auto', '7', {_ID}),
('order_shipping_address', 'auto', 'John Smith<br />Opencart-templates<br />1 Long Lane<br />London L12 1EW<br />Aberdeen<br />United Kingdom', {_ID}),
('order_total', 'auto', '$536.40', {_ID}),
('order_payment_address', 'auto', 'John Smith<br />Opencart-templates<br />1 Long Lane<br />London L12 1EW<br />Aberdeen<br />United Kingdom', {_ID}),
('order_date_added', 'auto', '2021-07-06 12:05:02', {_ID}),
('order_date', 'auto', '06/07/2021', {_ID}),
('order.date_modified', 'auto', '2021-07-06 11:36:47', {_ID}),
('order.accept_language', 'auto', 'en-GB,en-US;q=0.9,en;q=0.8', {_ID}),
('order.date_added', 'auto', '2021-07-06 11:35:29', {_ID}),
('order.user_agent', 'auto', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36', {_ID}),
('order.currency_value', 'auto', '1.00000000', {_ID}),
('order.ip', 'auto', '172.16.238.1', {_ID}),
('order.currency_code', 'auto', 'USD', {_ID}),
('order.currency_id', 'auto', '2', {_ID}),
('order.language_code', 'auto', 'en-gb', {_ID}),
('order.language_id', 'auto', '1', {_ID}),
('order.order_status_id', 'auto', '1', {_ID}),
('order.order_status', 'auto', 'Pending', {_ID}),
('order.commission', 'auto', '0.0000', {_ID}),
('order.total', 'auto', '536.4000', {_ID}),
('order.comment', 'auto', 'Test comments\nWith multi line.', {_ID}),
('order.shipping_code', 'auto', 'flat.flat', {_ID}),
('order.shipping_method', 'auto', 'Flat Shipping Rate', {_ID}),
('order.shipping_iso_code_3', 'auto', 'GBR', {_ID}),
('order.shipping_iso_code_2', 'auto', 'GB', {_ID}),
('order.shipping_country', 'auto', 'United Kingdom', {_ID}),
('order.shipping_country_id', 'auto', '222', {_ID}),
('order.shipping_zone', 'auto', 'Aberdeen', {_ID}),
('order.shipping_zone_code', 'auto', 'ABN', {_ID}),
('order.shipping_zone_id', 'auto', '3513', {_ID}),
('order.shipping_city', 'auto', 'London', {_ID}),
('order.shipping_postcode', 'auto', 'L12 1EW', {_ID}),
('order.shipping_company', 'auto', 'Opencart-templates', {_ID}),
('order.shipping_address_1', 'auto', '1 Long Lane', {_ID}),
('order.payment_code', 'auto', 'cod', {_ID}),
('order.shipping_firstname', 'auto', 'John', {_ID}),
('order.shipping_lastname', 'auto', 'Smith', {_ID}),
('order.payment_method', 'auto', 'Cash On Delivery', {_ID}),
('order.payment_country', 'auto', 'United Kingdom', {_ID}),
('order.payment_iso_code_2', 'auto', 'GB', {_ID}),
('order.payment_iso_code_3', 'auto', 'GBR', {_ID}),
('order', 'auto_serialize', 'YTo2Nzp7czo4OiJvcmRlcl9pZCI7czoyOiIxMCI7czoxMDoiaW52b2ljZV9ubyI7czoxOiIwIjtzOjE0OiJpbnZvaWNlX3ByZWZpeCI7czoxMToiSU5WLTIwMjEtMDAiO3M6ODoic3RvcmVfaWQiO3M6MToiMCI7czoxMDoic3RvcmVfbmFtZSI7czoxMDoiWW91ciBTdG9yZSI7czo5OiJzdG9yZV91cmwiO3M6Mzc6Imh0dHBzOi8vb3BlbmNhcnRfYWR2YW5jZWRfMzAyMS5sb2NhbC8iO3M6MTE6ImN1c3RvbWVyX2lkIjtzOjE6IjciO3M6MTI6ImFmZmlsaWF0ZV9pZCI7czoxOiIwIjtzOjE3OiJjdXN0b21lcl9ncm91cF9pZCI7czoxOiIxIjtzOjY6IndlaWdodCI7czoxMDoiMC4wMDAwMDAwMCI7czo5OiJmaXJzdG5hbWUiO3M6NDoiSm9obiI7czo4OiJsYXN0bmFtZSI7czo1OiJTbWl0aCI7czo1OiJlbWFpbCI7czoyODoib3BlbmNhcnQudGVtcGxhdGVzQGdtYWlsLmNvbSI7czo5OiJ0ZWxlcGhvbmUiO3M6MTA6IjAxMjM0NTY3ODkiO3M6MTI6ImN1c3RvbV9maWVsZCI7TjtzOjE3OiJwYXltZW50X2ZpcnN0bmFtZSI7czo0OiJKb2huIjtzOjE2OiJwYXltZW50X2xhc3RuYW1lIjtzOjU6IlNtaXRoIjtzOjE1OiJwYXltZW50X2NvbXBhbnkiO3M6MTg6Ik9wZW5jYXJ0LXRlbXBsYXRlcyI7czoxNzoicGF5bWVudF9hZGRyZXNzXzEiO3M6MTE6IjEgTG9uZyBMYW5lIjtzOjE3OiJwYXltZW50X2FkZHJlc3NfMiI7czowOiIiO3M6MTY6InBheW1lbnRfcG9zdGNvZGUiO3M6NzoiTDEyIDFFVyI7czoxMjoicGF5bWVudF9jaXR5IjtzOjY6IkxvbmRvbiI7czoxNToicGF5bWVudF96b25lX2lkIjtzOjQ6IjM1MTMiO3M6MTI6InBheW1lbnRfem9uZSI7czo4OiJBYmVyZGVlbiI7czoxNzoicGF5bWVudF96b25lX2NvZGUiO3M6MzoiQUJOIjtzOjE4OiJwYXltZW50X2NvdW50cnlfaWQiO3M6MzoiMjIyIjtzOjE1OiJwYXltZW50X2NvdW50cnkiO3M6MTQ6IlVuaXRlZCBLaW5nZG9tIjtzOjE4OiJwYXltZW50X2lzb19jb2RlXzIiO3M6MjoiR0IiO3M6MTg6InBheW1lbnRfaXNvX2NvZGVfMyI7czozOiJHQlIiO3M6MjI6InBheW1lbnRfYWRkcmVzc19mb3JtYXQiO3M6MDoiIjtzOjIwOiJwYXltZW50X2N1c3RvbV9maWVsZCI7YTowOnt9czoxNDoicGF5bWVudF9tZXRob2QiO3M6MTY6IkNhc2ggT24gRGVsaXZlcnkiO3M6MTI6InBheW1lbnRfY29kZSI7czozOiJjb2QiO3M6MTg6InNoaXBwaW5nX2ZpcnN0bmFtZSI7czo0OiJKb2huIjtzOjE3OiJzaGlwcGluZ19sYXN0bmFtZSI7czo1OiJTbWl0aCI7czoxNjoic2hpcHBpbmdfY29tcGFueSI7czoxODoiT3BlbmNhcnQtdGVtcGxhdGVzIjtzOjE4OiJzaGlwcGluZ19hZGRyZXNzXzEiO3M6MTE6IjEgTG9uZyBMYW5lIjtzOjE4OiJzaGlwcGluZ19hZGRyZXNzXzIiO3M6MDoiIjtzOjE3OiJzaGlwcGluZ19wb3N0Y29kZSI7czo3OiJMMTIgMUVXIjtzOjEzOiJzaGlwcGluZ19jaXR5IjtzOjY6IkxvbmRvbiI7czoxNjoic2hpcHBpbmdfem9uZV9pZCI7czo0OiIzNTEzIjtzOjEzOiJzaGlwcGluZ196b25lIjtzOjg6IkFiZXJkZWVuIjtzOjE4OiJzaGlwcGluZ196b25lX2NvZGUiO3M6MzoiQUJOIjtzOjE5OiJzaGlwcGluZ19jb3VudHJ5X2lkIjtzOjM6IjIyMiI7czoxNjoic2hpcHBpbmdfY291bnRyeSI7czoxNDoiVW5pdGVkIEtpbmdkb20iO3M6MTk6InNoaXBwaW5nX2lzb19jb2RlXzIiO3M6MjoiR0IiO3M6MTk6InNoaXBwaW5nX2lzb19jb2RlXzMiO3M6MzoiR0JSIjtzOjIzOiJzaGlwcGluZ19hZGRyZXNzX2Zvcm1hdCI7czowOiIiO3M6MjE6InNoaXBwaW5nX2N1c3RvbV9maWVsZCI7YTowOnt9czoxNToic2hpcHBpbmdfbWV0aG9kIjtzOjE4OiJGbGF0IFNoaXBwaW5nIFJhdGUiO3M6MTM6InNoaXBwaW5nX2NvZGUiO3M6OToiZmxhdC5mbGF0IjtzOjc6ImNvbW1lbnQiO3M6MzA6IlRlc3QgY29tbWVudHMKV2l0aCBtdWx0aSBsaW5lLiI7czo1OiJ0b3RhbCI7czo4OiI1MzYuNDAwMCI7czoxNToib3JkZXJfc3RhdHVzX2lkIjtzOjE6IjEiO3M6MTI6Im9yZGVyX3N0YXR1cyI7czo3OiJQZW5kaW5nIjtzOjEwOiJjb21taXNzaW9uIjtzOjY6IjAuMDAwMCI7czoxMToibGFuZ3VhZ2VfaWQiO3M6MToiMSI7czoxMzoibGFuZ3VhZ2VfY29kZSI7czo1OiJlbi1nYiI7czoxMToiY3VycmVuY3lfaWQiO3M6MToiMiI7czoxMzoiY3VycmVuY3lfY29kZSI7czozOiJVU0QiO3M6MTQ6ImN1cnJlbmN5X3ZhbHVlIjtzOjEwOiIxLjAwMDAwMDAwIjtzOjI6ImlwIjtzOjEyOiIxNzIuMTYuMjM4LjEiO3M6MTI6ImZvcndhcmRlZF9pcCI7czowOiIiO3M6MTA6InVzZXJfYWdlbnQiO3M6MTIxOiJNb3ppbGxhLzUuMCAoTWFjaW50b3NoOyBJbnRlbCBNYWMgT1MgWCAxMF8xNV83KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvOTAuMC40NDMwLjIxMiBTYWZhcmkvNTM3LjM2IjtzOjE1OiJhY2NlcHRfbGFuZ3VhZ2UiO3M6MjY6ImVuLUdCLGVuLVVTO3E9MC45LGVuO3E9MC44IjtzOjEwOiJkYXRlX2FkZGVkIjtzOjE5OiIyMDIxLTA3LTA2IDExOjM1OjI5IjtzOjEzOiJkYXRlX21vZGlmaWVkIjtzOjE5OiIyMDIxLTA3LTA2IDExOjM2OjQ3Ijt9', {_ID}),
('order.payment_country_id', 'auto', '222', {_ID}),
('order.payment_zone_code', 'auto', 'ABN', {_ID}),
('order.payment_zone', 'auto', 'Aberdeen', {_ID}),
('order.payment_zone_id', 'auto', '3513', {_ID}),
('order.payment_city', 'auto', 'London', {_ID}),
('order.payment_postcode', 'auto', 'L12 1EW', {_ID}),
('order.payment_address_1', 'auto', '1 Long Lane', {_ID}),
('order.payment_company', 'auto', 'Opencart-templates', {_ID}),
('order.payment_lastname', 'auto', 'Smith', {_ID}),
('order.payment_firstname', 'auto', 'John', {_ID}),
('order.telephone', 'auto', '0123456789', {_ID}),
('order.email', 'auto', 'user@oc.local', {_ID}),
('order.lastname', 'auto', 'Smith', {_ID}),
('order.firstname', 'auto', 'John', {_ID}),
('order.weight', 'auto', '0.00000000', {_ID}),
('order.customer_group_id', 'auto', '1', {_ID}),
('order.affiliate_id', 'auto', '0', {_ID}),
('order.customer_id', 'auto', '7', {_ID}),
('order.store_url', 'auto', 'https://oc.local/', {_ID}),
('order.store_name', 'auto', 'Your Store', {_ID}),
('order.store_id', 'auto', '0', {_ID}),
('order.invoice_prefix', 'auto', 'INV-2021-00', {_ID}),
('order.invoice_no', 'auto', '0', {_ID}),
('order.order_id', 'auto', '10', {_ID}),
('date_modified', 'auto', '2021-07-06 12:05:02', {_ID}),
('date_added', 'auto', '2021-07-06 12:05:02', {_ID}),
('date_ordered', 'auto', '2021-07-06', {_ID}),
('status', 'auto', 'Awaiting Products', {_ID}),
('reason', 'auto', 'Faulty, please supply details', {_ID}),
('opened', 'auto', 'No', {_ID}),
('quantity', 'auto', '1', {_ID}),
('model', 'auto', 'Product 3', {_ID}),
('product', 'auto', 'Canon EOS 5D', {_ID}),
('telephone', 'auto', '0123456789', {_ID}),
('email', 'auto', 'user@oc.local', {_ID}),
('lastname', 'auto', 'Smith', {_ID}),
('firstname', 'auto', 'John', {_ID}),
('order_id', 'auto', '10', {_ID}),
('return_id', 'auto', '2', {_ID}),
('wrapper_tpl', 'auto', '_main.twig', {_ID}),
('privacy_url', 'auto', 'https://oc.local/index.php?route=information/information&amp;information_id=3', {_ID}),
('home_url', 'auto', 'https://oc.local/index.php?route=common/home', {_ID}),
('contact_url', 'auto', 'https://oc.local/index.php?route=information/contact', {_ID}),
('cart_url', 'auto', 'https://oc.local/index.php?route=checkout/cart', {_ID}),
('login_url', 'auto', 'https://oc.local/index.php?route=account/login', {_ID}),
('datetime_now', 'auto', 'Tuesday 06th July 2021', {_ID}),
('date_now', 'auto', '06/07/2021', {_ID}),
('lang', 'auto', 'en', {_ID}),
('store_theme_dir', 'auto', 'default/extension/module/emailtemplate/', {_ID}),
('store_customer_price', 'auto', '0', {_ID}),
('store_theme', 'auto', 'default', {_ID}),
('store_tax_default', 'auto', 'shipping', {_ID}),
('store_tax', 'auto', '1', {_ID}),
('store_zone_id', 'auto', '3563', {_ID}),
('store_currency', 'auto', 'USD', {_ID}),
('store_country_id', 'auto', '222', {_ID}),
('store_telephone', 'auto', '123456789', {_ID}),
('store_email', 'auto', 'store@localhost', {_ID}),
('store_address', 'auto', 'Address 1', {_ID}),
('store_owner', 'auto', 'Your Name', {_ID}),
('store_ssl', 'auto', 'https://oc.local/', {_ID}),
('store_url', 'auto', 'https://oc.local/', {_ID}),
('store_name', 'auto', 'Your Store', {_ID}),
('store_title', 'auto', 'Your Store', {_ID}),
('ip', 'auto', '172.16.238.1', {_ID}),
('customer_email', 'auto', 'user@oc.local', {_ID}),
('customer_id', 'auto', '7', {_ID}),
('customer_group_id', 'auto', '1', {_ID}),
('language_id', 'auto', '1', {_ID}),
('store_id', 'auto', '0', {_ID});