INSERT INTO `oc_emailtemplate_shortcode` (`emailtemplate_shortcode_code`, `emailtemplate_shortcode_type`, `emailtemplate_shortcode_example`, `emailtemplate_id`) VALUES
('store_id', 'auto', '0', {_ID}),
('language_id', 'auto', '1', {_ID}),
('customer_group_id', 'auto', '1', {_ID}),
('customer_id', 'auto', '7', {_ID}),
('customer_email', 'auto', 'user@oc.local', {_ID}),
('ip', 'auto', '172.16.238.1', {_ID}),
('store_title', 'auto', 'Your Store', {_ID}),
('store_name', 'auto', 'Your Store', {_ID}),
('store_url', 'auto', 'https://oc.local/', {_ID}),
('store_ssl', 'auto', 'https://oc.local/', {_ID}),
('store_owner', 'auto', 'Your Name', {_ID}),
('store_address', 'auto', 'Address 1', {_ID}),
('store_email', 'auto', 'store@localhost', {_ID}),
('store_telephone', 'auto', '123456789', {_ID}),
('store_country_id', 'auto', '222', {_ID}),
('store_currency', 'auto', 'USD', {_ID}),
('store_zone_id', 'auto', '3563', {_ID}),
('store_tax', 'auto', '1', {_ID}),
('store_tax_default', 'auto', 'shipping', {_ID}),
('store_theme', 'auto', 'default', {_ID}),
('store_customer_price', 'auto', '0', {_ID}),
('payment_method', 'auto', 'bank_transfer', {_ID}),
('store_theme_dir', 'auto', 'default/extension/module/emailtemplate/', {_ID}),
('lang', 'auto', 'en', {_ID}),
('date_now', 'auto', '06/07/2021', {_ID}),
('datetime_now', 'auto', 'Tuesday 06th July 2021', {_ID}),
('login_url', 'auto', 'https://oc.local/index.php?route=account/login', {_ID}),
('cart_url', 'auto', 'https://oc.local/index.php?route=checkout/cart', {_ID}),
('contact_url', 'auto', 'https://oc.local/index.php?route=information/contact', {_ID}),
('home_url', 'auto', 'https://oc.local/index.php?route=common/home', {_ID}),
('privacy_url', 'auto', 'https://oc.local/index.php?route=information/information&amp;information_id=3', {_ID}),
('wrapper_tpl', 'auto', '_main.twig', {_ID}),
('voucher_id', 'auto', '3', {_ID}),
('order_id', 'auto', '13', {_ID}),
('from_name', 'auto', 'John Smith', {_ID}),
('from_email', 'auto', 'user@oc.local', {_ID}),
('to_name', 'auto', 'Harry Redknapp', {_ID}),
('to_email', 'auto', 'harry@redknapp.com', {_ID}),
('voucher_theme_id', 'auto', '7', {_ID}),
('message', 'auto', 'Happy Birthday Harry', {_ID}),
('amount', 'auto', '$100.00', {_ID}),
('status', 'auto', '1', {_ID}),
('date_added', 'auto', '2021-07-06 12:05:02', {_ID}),
('image', 'auto', 'https://oc.local/image/catalog/demo/gift-voucher-birthday.jpg', {_ID}),
('name', 'auto', 'Birthday', {_ID}),
('theme', 'auto', 'Birthday', {_ID}),
('title', 'auto', 'You have been sent a gift certificate from John Smith', {_ID}),
('order_invoice_no', 'auto', '0', {_ID}),
('order_invoice_prefix', 'auto', 'INV-2021-00', {_ID}),
('order_store_id', 'auto', '0', {_ID}),
('order_store_name', 'auto', 'Your Store', {_ID}),
('order_store_url', 'auto', 'https://oc.local/', {_ID}),
('order_customer_id', 'auto', '7', {_ID}),
('order_affiliate_id', 'auto', '0', {_ID}),
('order_customer_group_id', 'auto', '1', {_ID}),
('order_weight', 'auto', '0.00000000', {_ID}),
('order_firstname', 'auto', 'John', {_ID}),
('order_lastname', 'auto', 'Smith', {_ID}),
('order_email', 'auto', 'user@oc.local', {_ID}),
('order_telephone', 'auto', '0123456789', {_ID}),
('order_payment_firstname', 'auto', 'John', {_ID}),
('order_payment_lastname', 'auto', 'Smith', {_ID}),
('order_payment_company', 'auto', 'Opencart-templates', {_ID}),
('order_payment_address_1', 'auto', '1 Long Lane', {_ID}),
('order_payment_postcode', 'auto', 'L12 1EW', {_ID}),
('order_payment_city', 'auto', 'London', {_ID}),
('order_payment_zone_id', 'auto', '3513', {_ID}),
('order_payment_zone', 'auto', 'Aberdeen', {_ID}),
('order_payment_zone_code', 'auto', 'ABN', {_ID}),
('order_payment_country_id', 'auto', '222', {_ID}),
('order_payment_country', 'auto', 'United Kingdom', {_ID}),
('order_payment_iso_code_2', 'auto', 'GB', {_ID}),
('order_payment_iso_code_3', 'auto', 'GBR', {_ID}),
('order_payment_method', 'auto', 'Bank Transfer', {_ID}),
('order_payment_code', 'auto', 'bank_transfer', {_ID}),
('order_shipping_zone_id', 'auto', '0', {_ID}),
('order_shipping_country_id', 'auto', '0', {_ID}),
('order_total', 'auto', '$100.00', {_ID}),
('order_status_id', 'auto', '5', {_ID}),
('order_status', 'auto', 'Complete', {_ID}),
('order_commission', 'auto', '0.0000', {_ID}),
('order_language_id', 'auto', '1', {_ID}),
('order_language_code', 'auto', 'en-gb', {_ID}),
('order_currency_id', 'auto', '2', {_ID}),
('order_currency_code', 'auto', 'USD', {_ID}),
('order_currency_value', 'auto', '1.00000000', {_ID}),
('order_ip', 'auto', '172.16.238.1', {_ID}),
('order_user_agent', 'auto', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36', {_ID}),
('order_accept_language', 'auto', 'en-GB,en-US;q=0.9,en;q=0.8', {_ID}),
('order_date_added', 'auto', '2021-07-06 12:05:02', {_ID}),
('order_date_modified', 'auto', '2021-07-06 11:49:20', {_ID}),
('image_width', 'auto', '300', {_ID}),
('image_height', 'auto', '199', {_ID}),
('voucher_url', 'auto', 'https://oc.local/', {_ID}),
('voucher_url_text', 'auto', 'https://oc.local/', {_ID}),
('preference_text', 'auto', '<div>You\'re receiving this email because of your <a href=\"https://oc.local/\">Your Store</a> account. <a href=\"\">Manage your email preference</a> | <a href=\"https://oc.local/index.php?route=information/information&amp;information_id=3\">Privacy policy</a></div>', {_ID}),
('code', 'language', 'en', {_ID}),
('direction', 'language', 'ltr', {_ID}),
('date_format_short', 'language', 'd/m/Y', {_ID}),
('date_format_long', 'language', 'l dS F Y', {_ID}),
('time_format', 'language', 'h:i:s A', {_ID}),
('datetime_format', 'language', 'd/m/Y H:i:s', {_ID}),
('text_home', 'language', '<i class=\"fa fa-home\"></i>', {_ID}),
('text_yes', 'language', 'Yes', {_ID}),
('text_no', 'language', 'No', {_ID}),
('text_all_zones', 'language', 'All Zones', {_ID}),
('text_pagination', 'language', 'Showing %d to %d of %d (%d Pages)', {_ID}),
('text_no_results', 'language', 'No results!', {_ID}),
('button_address_add', 'language', 'Add Address', {_ID}),
('button_back', 'language', 'Back', {_ID}),
('button_continue', 'language', 'Continue', {_ID}),
('button_cart', 'language', 'Add to Cart', {_ID}),
('button_cancel', 'language', 'Cancel', {_ID}),
('button_compare', 'language', 'Compare this Product', {_ID}),
('button_wishlist', 'language', 'Add to Wish List', {_ID}),
('button_checkout', 'language', 'Checkout', {_ID}),
('button_confirm', 'language', 'Confirm Order', {_ID}),
('button_coupon', 'language', 'Apply Coupon', {_ID}),
('button_delete', 'language', 'Delete', {_ID}),
('button_download', 'language', 'Download', {_ID}),
('button_edit', 'language', 'Edit', {_ID}),
('button_filter', 'language', 'Refine Search', {_ID}),
('button_new_address', 'language', 'New Address', {_ID}),
('button_change_address', 'language', 'Change Address', {_ID}),
('button_reviews', 'language', 'Reviews', {_ID}),
('button_write', 'language', 'Write Review', {_ID}),
('button_login', 'language', 'Login', {_ID}),
('button_update', 'language', 'Update', {_ID}),
('button_remove', 'language', 'Remove', {_ID}),
('button_reorder', 'language', 'Reorder', {_ID}),
('button_return', 'language', 'Return', {_ID}),
('button_shopping', 'language', 'Continue Shopping', {_ID}),
('button_search', 'language', 'Search', {_ID}),
('button_shipping', 'language', 'Apply Shipping', {_ID}),
('button_submit', 'language', 'Submit', {_ID}),
('button_guest', 'language', 'Guest Checkout', {_ID}),
('button_view', 'language', 'View', {_ID}),
('button_voucher', 'language', 'Apply Gift Certificate', {_ID}),
('button_upload', 'language', 'Upload File', {_ID}),
('button_reward', 'language', 'Apply Points', {_ID}),
('button_quote', 'language', 'Get Quotes', {_ID}),
('button_list', 'language', 'List', {_ID}),
('button_grid', 'language', 'Grid', {_ID}),
('button_map', 'language', 'View Google Map', {_ID}),
('error_exception', 'language', 'Error Code(%s): %s in %s on line %s', {_ID}),
('error_upload_1', 'language', 'Warning: The uploaded file exceeds the upload_max_filesize directive in php.ini!', {_ID}),
('error_upload_2', 'language', 'Warning: The uploaded file exceeds the MAX_FILE_SIZE directive that was specified in the HTML form!', {_ID}),
('error_upload_3', 'language', 'Warning: The uploaded file was only partially uploaded!', {_ID}),
('error_upload_4', 'language', 'Warning: No file was uploaded!', {_ID}),
('error_upload_6', 'language', 'Warning: Missing a temporary folder!', {_ID}),
('error_upload_7', 'language', 'Warning: Failed to write file to disk!', {_ID}),
('error_upload_8', 'language', 'Warning: File upload stopped by extension!', {_ID}),
('error_upload_999', 'language', 'Warning: No error code available!', {_ID}),
('error_curl', 'language', 'CURL: Error Code(%s): %s', {_ID}),
('datepicker', 'language', 'en-gb', {_ID}),
('button_cart_checkout', 'language', 'Finish Order', {_ID}),
('text_emailtemplate_cart_title', 'language', '{{ customer_firstname }} you\'ve left something in your cart', {_ID}),
('text_emailtemplate_footer', 'language', '&lt;div&gt;\r\n&lt;table cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; style=&quot;width:100%&quot;&gt;\r\n	&lt;tbody&gt;\r\n		&lt;tr&gt;\r\n			&lt;td height=&quot;10&quot; style=&quot;font-size:1px; line-height:10px; mso-margin-top-alt:1px&quot;&gt;&amp;nbsp;&lt;/td&gt;\r\n		&lt;/tr&gt;\r\n		&lt;tr&gt;\r\n			&lt;td style=&quot;color:#666666; font-size:13px&quot;&gt;If you have any questions please do not hesitate to contact us via our &lt;a href=&quot;{{ contact_url }}&quot;&gt;website contact us form&lt;/a&gt;, email: &lt;a href=&quot;mailto:{{ store_email }}&quot;&gt;{{ store_email }}&lt;/a&gt; or phone us on &lt;a href=&quot;tel:{{ store_telephone }}&quot; style=&quot;    white-space: nowrap;&quot;&gt;{{ store_telephone }}&lt;/a&gt; and we will be happy to help.&amp;nbsp;&lt;/td&gt;\r\n		&lt;/tr&gt;\r\n		&lt;tr&gt;\r\n			&lt;td height=&quot;5&quot; style=&quot;font-size:1px; line-height:5px; mso-margin-top-alt:1px&quot;&gt;&amp;nbsp;&lt;/td&gt;\r\n		&lt;/tr&gt;\r\n		&lt;tr&gt;\r\n			&lt;td&gt;&lt;strong&gt;{{ store_name }}&lt;/strong&gt;&lt;/td&gt;\r\n		&lt;/tr&gt;\r\n	&lt;/tbody&gt;\r\n&lt;/table&gt;\r\n&lt;/div&gt;\r\n', {_ID}),
('text_price', 'language', 'Price', {_ID}),
('text_product', 'language', 'Product', {_ID}),
('text_quantity', 'language', 'Quantity', {_ID}),
('text_rating', 'language', 'Rating', {_ID}),
('text_total', 'language', 'Total', {_ID}),
('text_view_browser', 'language', 'If you\'re having difficulty viewing this email <a href=\"%s\" target=\"_blank\">open in a browser</a>.', {_ID}),
('text_heading', 'language', 'Gift Certificate', {_ID}),
('text_subject', 'language', 'You have been sent a gift certificate from %s', {_ID}),
('text_greeting', 'language', 'Congratulations, You have received a Gift Certificate worth %s', {_ID}),
('text_from', 'language', 'This Gift Certificate has been sent to you by %s', {_ID}),
('text_message', 'language', 'With a message saying', {_ID}),
('text_redeem', 'language', 'To redeem this Gift Certificate, write down the redemption code which is <b>%s</b> then click on the the link below and purchase the product you wish to use this gift certificate on. You can enter the gift certificate code on the shopping cart page before you click checkout.', {_ID}),
('text_footer', 'language', 'Please reply to this e-mail if you have any questions.', {_ID});