INSERT INTO `oc_emailtemplate_shortcode` (`emailtemplate_shortcode_code`, `emailtemplate_shortcode_type`, `emailtemplate_shortcode_example`, `emailtemplate_id`) VALUES
('store_id', 'auto', '0', {_ID}),
('language_id', 'auto', '1', {_ID}),
('customer_group_id', 'auto', '1', {_ID}),
('customer_id', 'auto', '7', {_ID}),
('customer_email', 'auto', 'user@oc.local', {_ID}),
('ip', 'auto', '172.16.238.1', {_ID}),
('store_title', 'auto', 'Your Store', {_ID}),
('store_name', 'auto', 'Your Store', {_ID}),
('store_url', 'auto', 'https://oc.local/', {_ID}),
('store_ssl', 'auto', 'https://oc.local/', {_ID}),
('store_owner', 'auto', 'Your Name', {_ID}),
('store_address', 'auto', 'Address 1', {_ID}),
('store_email', 'auto', 'store@localhost', {_ID}),
('store_telephone', 'auto', '123456789', {_ID}),
('store_country_id', 'auto', '222', {_ID}),
('store_currency', 'auto', 'USD', {_ID}),
('store_zone_id', 'auto', '3563', {_ID}),
('store_tax', 'auto', '1', {_ID}),
('store_tax_default', 'auto', 'shipping', {_ID}),
('store_theme', 'auto', 'default', {_ID}),
('store_customer_price', 'auto', '0', {_ID}),
('store_theme_dir', 'auto', 'default/extension/module/emailtemplate/', {_ID}),
('lang', 'auto', 'en', {_ID}),
('date_now', 'auto', '06/07/2021', {_ID}),
('datetime_now', 'auto', 'Tuesday 06th July 2021', {_ID}),
('login_url', 'auto', 'https://oc.local/index.php?route=account/login', {_ID}),
('cart_url', 'auto', 'https://oc.local/index.php?route=checkout/cart', {_ID}),
('contact_url', 'auto', 'https://oc.local/index.php?route=information/contact', {_ID}),
('home_url', 'auto', 'https://oc.local/index.php?route=common/home', {_ID}),
('privacy_url', 'auto', 'https://oc.local/index.php?route=information/information&amp;information_id=3', {_ID}),
('wrapper_tpl', 'auto', '_main.twig', {_ID}),
('review_name', 'auto', 'John†Smith', {_ID}),
('review_text', 'auto', 'The quality feels really good. Hope it last a long time. ', {_ID}),
('review_rating', 'auto', '5', {_ID}),
('review_captcha', 'auto', '480401', {_ID}),
('product_id', 'auto', '30', {_ID}),
('product_name', 'auto', 'Canon EOS 5D', {_ID}),
('product_description', 'auto', '&lt;p&gt;\r\n	Canon\'s press material for the EOS 5D states that it \'defines (a) new D-SLR category\', while we\'re not typically too concerned with marketing talk this particular statement is clearly pretty accurate. The EOS 5D is unlike any previous digital SLR in that it combines a full-frame (35 mm sized) high resolution sensor (12.8 megapixels) with a relatively compact body (slightly larger than the EOS 20D, although in your hand it feels noticeably \'chunkier\'). The EOS 5D is aimed to slot in between the EOS 20D and the EOS-1D professional digital SLR\'s, an important difference when compared to the latter is that the EOS 5D doesn\'t have any environmental seals. While Canon don\'t specifically refer to the EOS 5D as a \'professional\' digital SLR it will have obvious appeal to professionals who want a high quality digital SLR in a body lighter than the EOS-1D. It will also no doubt appeal to current EOS 20D owners (although lets hope they\'ve not bought too many EF-S lenses...) ‰Î&lt;/p&gt;\r\n', {_ID}),
('product_meta_title', 'auto', 'sdf', {_ID}),
('product_model', 'auto', 'Product 3', {_ID}),
('product_quantity', 'auto', '5', {_ID}),
('product_stock_status', 'auto', '2-3 Days', {_ID}),
('product_image', 'auto', 'catalog/demo/canon_eos_5d_1.jpg', {_ID}),
('product_manufacturer_id', 'auto', '9', {_ID}),
('product_manufacturer', 'auto', 'Canon', {_ID}),
('product_price', 'auto', '100.0000', {_ID}),
('product_special', 'auto', '80.0000', {_ID}),
('product_reward', 'auto', '200', {_ID}),
('product_points', 'auto', '0', {_ID}),
('product_tax_class_id', 'auto', '9', {_ID}),
('product_date_available', 'auto', '2021-07-06 12:05:02', {_ID}),
('product_weight', 'auto', '0.00000000', {_ID}),
('product_weight_class_id', 'auto', '1', {_ID}),
('product_length', 'auto', '0.00000000', {_ID}),
('product_width', 'auto', '0.00000000', {_ID}),
('product_height', 'auto', '0.00000000', {_ID}),
('product_length_class_id', 'auto', '1', {_ID}),
('product_subtract', 'auto', '1', {_ID}),
('product_rating', 'auto', '0', {_ID}),
('product_reviews', 'auto', '0', {_ID}),
('product_minimum', 'auto', '1', {_ID}),
('product_sort_order', 'auto', '0', {_ID}),
('product_status', 'auto', '1', {_ID}),
('product_date_added', 'auto', '2021-07-06 12:05:02', {_ID}),
('product_date_modified', 'auto', '2021-07-06 12:05:02', {_ID}),
('product_viewed', 'auto', '4', {_ID}),
('review_approve', 'auto', 'https://oc.local/admin/index.php?route=catalog/review/edit&review_id=1', {_ID}),
('review_approve_text', 'auto', 'https://oc.local/admin/index.php?route=catalog/review/edit&review_id=1', {_ID}),
('customer_link', 'auto', 'https://oc.local/admin/index.php?route=customer/customer/edit&filter_name=John%C2%A0Smith', {_ID}),
('customer_link_text', 'auto', 'https://oc.local/admin/index.php?route=customer/customer/edit&filter_name=John%C2%A0Smith', {_ID}),
('product_link', 'auto', 'https://oc.local/index.php?route=product/product&amp;product_id=30', {_ID}),
('code', 'language', 'en', {_ID}),
('direction', 'language', 'ltr', {_ID}),
('date_format_short', 'language', 'd/m/Y', {_ID}),
('date_format_long', 'language', 'l dS F Y', {_ID}),
('time_format', 'language', 'h:i:s A', {_ID}),
('datetime_format', 'language', 'd/m/Y H:i:s', {_ID}),
('text_home', 'language', '<i class=\"fa fa-home\"></i>', {_ID}),
('text_yes', 'language', 'Yes', {_ID}),
('text_no', 'language', 'No', {_ID}),
('text_all_zones', 'language', 'All Zones', {_ID}),
('text_pagination', 'language', 'Showing %d to %d of %d (%d Pages)', {_ID}),
('text_no_results', 'language', 'No results!', {_ID}),
('button_address_add', 'language', 'Add Address', {_ID}),
('button_back', 'language', 'Back', {_ID}),
('button_continue', 'language', 'Continue', {_ID}),
('button_cart', 'language', 'Add to Cart', {_ID}),
('button_cancel', 'language', 'Cancel', {_ID}),
('button_compare', 'language', 'Compare this Product', {_ID}),
('button_wishlist', 'language', 'Add to Wish List', {_ID}),
('button_checkout', 'language', 'Checkout', {_ID}),
('button_confirm', 'language', 'Confirm Order', {_ID}),
('button_coupon', 'language', 'Apply Coupon', {_ID}),
('button_delete', 'language', 'Delete', {_ID}),
('button_download', 'language', 'Download', {_ID}),
('button_edit', 'language', 'Edit', {_ID}),
('button_filter', 'language', 'Refine Search', {_ID}),
('button_new_address', 'language', 'New Address', {_ID}),
('button_change_address', 'language', 'Change Address', {_ID}),
('button_reviews', 'language', 'Reviews', {_ID}),
('button_write', 'language', 'Write Review', {_ID}),
('button_login', 'language', 'Login', {_ID}),
('button_update', 'language', 'Update', {_ID}),
('button_remove', 'language', 'Remove', {_ID}),
('button_reorder', 'language', 'Reorder', {_ID}),
('button_return', 'language', 'Return', {_ID}),
('button_shopping', 'language', 'Continue Shopping', {_ID}),
('button_search', 'language', 'Search', {_ID}),
('button_shipping', 'language', 'Apply Shipping', {_ID}),
('button_submit', 'language', 'Submit', {_ID}),
('button_guest', 'language', 'Guest Checkout', {_ID}),
('button_view', 'language', 'View', {_ID}),
('button_voucher', 'language', 'Apply Gift Certificate', {_ID}),
('button_upload', 'language', 'Upload File', {_ID}),
('button_reward', 'language', 'Apply Points', {_ID}),
('button_quote', 'language', 'Get Quotes', {_ID}),
('button_list', 'language', 'List', {_ID}),
('button_grid', 'language', 'Grid', {_ID}),
('button_map', 'language', 'View Google Map', {_ID}),
('error_exception', 'language', 'Error Code(%s): %s in %s on line %s', {_ID}),
('error_upload_1', 'language', 'Warning: The uploaded file exceeds the upload_max_filesize directive in php.ini!', {_ID}),
('error_upload_2', 'language', 'Warning: The uploaded file exceeds the MAX_FILE_SIZE directive that was specified in the HTML form!', {_ID}),
('error_upload_3', 'language', 'Warning: The uploaded file was only partially uploaded!', {_ID}),
('error_upload_4', 'language', 'Warning: No file was uploaded!', {_ID}),
('error_upload_6', 'language', 'Warning: Missing a temporary folder!', {_ID}),
('error_upload_7', 'language', 'Warning: Failed to write file to disk!', {_ID}),
('error_upload_8', 'language', 'Warning: File upload stopped by extension!', {_ID}),
('error_upload_999', 'language', 'Warning: No error code available!', {_ID}),
('error_curl', 'language', 'CURL: Error Code(%s): %s', {_ID}),
('datepicker', 'language', 'en-gb', {_ID}),
('button_cart_checkout', 'language', 'Finish Order', {_ID}),
('text_emailtemplate_cart_title', 'language', '{{ customer_firstname }} you\'ve left something in your cart', {_ID}),
('text_emailtemplate_footer', 'language', '&lt;div&gt;\r\n&lt;table cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; style=&quot;width:100%&quot;&gt;\r\n	&lt;tbody&gt;\r\n		&lt;tr&gt;\r\n			&lt;td height=&quot;10&quot; style=&quot;font-size:1px; line-height:10px; mso-margin-top-alt:1px&quot;&gt;&amp;nbsp;&lt;/td&gt;\r\n		&lt;/tr&gt;\r\n		&lt;tr&gt;\r\n			&lt;td style=&quot;color:#666666; font-size:13px&quot;&gt;If you have any questions please do not hesitate to contact us via our &lt;a href=&quot;{{ contact_url }}&quot;&gt;website contact us form&lt;/a&gt;, email: &lt;a href=&quot;mailto:{{ store_email }}&quot;&gt;{{ store_email }}&lt;/a&gt; or phone us on &lt;a href=&quot;tel:{{ store_telephone }}&quot; style=&quot;    white-space: nowrap;&quot;&gt;{{ store_telephone }}&lt;/a&gt; and we will be happy to help.&amp;nbsp;&lt;/td&gt;\r\n		&lt;/tr&gt;\r\n		&lt;tr&gt;\r\n			&lt;td height=&quot;5&quot; style=&quot;font-size:1px; line-height:5px; mso-margin-top-alt:1px&quot;&gt;&amp;nbsp;&lt;/td&gt;\r\n		&lt;/tr&gt;\r\n		&lt;tr&gt;\r\n			&lt;td&gt;&lt;strong&gt;{{ store_name }}&lt;/strong&gt;&lt;/td&gt;\r\n		&lt;/tr&gt;\r\n	&lt;/tbody&gt;\r\n&lt;/table&gt;\r\n&lt;/div&gt;\r\n', {_ID}),
('text_price', 'language', 'Price', {_ID}),
('text_product', 'language', 'Product: %s', {_ID}),
('text_quantity', 'language', 'Quantity', {_ID}),
('text_rating', 'language', 'Rating: %s', {_ID}),
('text_total', 'language', 'Total', {_ID}),
('text_view_browser', 'language', 'If you\'re having difficulty viewing this email <a href=\"%s\" target=\"_blank\">open in a browser</a>.', {_ID}),
('text_subject', 'language', '{{ product_name }} - Product Review', {_ID}),
('text_waiting', 'language', 'You have a new product review waiting.', {_ID}),
('text_reviewer', 'language', 'Reviewer: %s', {_ID}),
('text_review', 'language', 'Review Text:', {_ID}),
('text_review_approve', 'language', 'To approve review click on the link below', {_ID}),
('text_review_heading', 'language', 'New review awaiting approval for: %s', {_ID}),
('text_review_message', 'language', 'Message:', {_ID}),
('text_review_product', 'language', 'Product:', {_ID}),
('text_review_customer', 'language', 'Customer:', {_ID}),
('text_review_rating', 'language', 'Rating:', {_ID}),
('text_review_review', 'language', 'You have received a new review for', {_ID}),
('text_review_reviewer', 'language', 'Reviewer:', {_ID});